all: taskmanager.exe

taskmanager.exe: main.o processes.o
	gcc -o taskmanager.exe main.o processes.o

processes.o: processes.c processes.h
	gcc -c processes.c

main.o: main.c processes.h
	gcc -c main.c

clean:
	del /f *.o *.exe